---
title: "Practical Machine Learning"
author: "Weronika Kusnierczak"
date: "March 23, 2016"
output: html_document
---

#Intraduction

This is a Course Project for Practical Machine Learning course in Coursera built on the data from:http://groupware.les.inf.puc-rio.br/har

#Loading the packages

```{r, echo=TRUE}
library(caret)
library(randomForest)
library(e1071)
```

#Preparing the dataset

```{r,echo=TRUE}
url_train <- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv'
url_test <- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv'
download.file(url = url_train, destfile = 'data_train.csv')
download.file(url = url_test, destfile = 'data_test.csv')
pml_train <- read.csv(file = 'data_train.csv',na.strings = c('NA','#DIV/0!',''))
pml_quiz <- read.csv(file = 'data_test.csv',na.strings = c('NA','#DIV/0!',''))
```

#Deleting columns with null values, creating a loop

```{r,echo=TRUE}
for(i in c(8:ncol(pml_train)-1)) {
        pml_train[,i] = as.numeric(as.character(pml_train[,i]))
        pml_quiz[,i] = as.numeric(as.character(pml_quiz[,i]))
}
feature_index <- colnames(pml_train)
feature_index <- colnames(pml_train[colSums(is.na(pml_train)) == 0])
feature_index <- feature_index[-c(1:7)]
```

#Dividing dataset into test and cross-validation

```{r,echo=TRUE}
set.seed(1300)
index_train <- createDataPartition(y=pml_train$classe, p=0.80, list=FALSE)
data_train <- pml_train[index_train,feature_index]
data_xval <- pml_train[-index_train,feature_index]
dim(data_train); dim(data_xval)
```

#Train model & cross-validation

```{r,echo=TRUE}
mod_rf <- train(classe ~ .,
                data = data_train, 
                method = 'rf', 
                trControl = trainControl(method = "cv", 
                                         number = 4, 
                                         allowParallel = TRUE, 
                                         verboseIter = TRUE))
pred_rf <- predict(mod_rf,data_xval)
cm_rf <- confusionMatrix(pred_rf,data_xval$classe)
```

#Prediction against cross-validation

```{r,echo=TRUE}
cm_rf
```

#Applying model to test from quiz

```{r,echo=TRUE}
final_col <- length(colnames(pml_quiz[]))
colnames(pml_quiz)[final_col] <- 'classe'
quiz_rf <- predict(mod_rf,pml_quiz[,feature_index])
quiz_rf
```